### ISSUE TITLE
Web app not working

### ISSUE THREAD

**Issue by sailendraw** [tugbadogan/hotelmanagement#1]
Hello there
i recently downloaded your webapp but cannot use it on my localhost,,how can use it on my local host

**Comment by amitommishra** [comment]
+1 .. Same here..

**Comment by tugbadogan** [comment]
Have you setup apache server ? 
Then, you should edit following file's 17th line. Change it to your hostname (http://localhost/ if you are installing your local machine)
https://github.com/tugbadogan/hotelmanagement/blob/master/application/config/config.php

**Comment by amitommishra** [comment]
I was trying to do it in WAMP server. even i tried changing the config
file.... still no luck :( Can i have your email id where we can chat ?

Thanks and Regards
Amit Om Mishra

**Comment by jbiuk** [comment]
Hi,

something is not working with this app, i invested a lot of effort to make it run but i failed.

I have LAMP server, with FastCgi on it. 
Made the changes in config.php and database.php(changed the user/pass parameters).

Seems somethig with login redirection is not working correctly.
Opening url http://localhost/ app redirects me to http://localhost/login but there i get 404.

When i try to open http://localhost/index.php/login page brakes but shows partialy both login and welcome screen.

Hope you can help me out.

Cheers,
Jura

**Comment by tugbadogan** [comment]
You should edit rewrite rules on your LAMP server @jbiuk 

If you use apache server add following lines to your .htaccess file

```
RewriteEngine on
RewriteCond $1 !^(index\.php|images|robots\.txt)
RewriteRule ^(.*)$ /index.php/$1 [L]
```

If you're using nginx server add following lines to your configuration file (For example: /etc/nginx/sites-available/yourdomain.com.vhost)

```
location / {
    # Check if a file exists, or route it to index.php.
    try_files $uri $uri/ /index.php;
}
```

@amitommishra : If you say the problem like @jbiuk  said, I can help you here too

**Comment by jbiuk** [comment]
Thank you for your response!

I created new .htaccess file in my  apache root folder "/var/www/.htaccess", and added the rules as you said.
Defined mile.php as my index page in config.php.
Page showed something that was not in order, for "http://192.168.1.5/hotel/mile.php/login"

![image](https://cloud.githubusercontent.com/assets/6275878/5603969/5f69f3fc-939f-11e4-9a3c-16a6dfa2dc33.png)

In my consle, on Crome broswer, i got the folowing errors when tried to open the login page:

 Failed to load resource: the server responded with a status of 404 (Not Found)
login:278 Uncaught SyntaxError: Unexpected token <
login:328 Uncaught ReferenceError: guidely is not defined 

When i open the login file in script for line 277 and 278 i saw this:

```
    var lineChartData = {
        labels: <? echo json_encode($next_week_freq['dates']);?>,
```

I am new to javascript so i am unsure if this is correct syntax? 

There are many .htaccess files in CI folders, should i change them all?

**Comment by amitommishra** [comment]
@jbiuk  That is the problem with php short tags. Please follow below mentioned i got it working after making changes in php.ini however my suggestions would be for keeping future release in mind to use <?php :) 

http://stackoverflow.com/questions/12579448/php-short-open-tag-on-not-working

@tugbadogan : Thank you. your comments above did the trick. I got it working till login page :)

**Comment by jbiuk** [comment]
Hi,
thank you guys for your help so far, i got it working till login page :-)

Also i noticed that in code threre should be some users present in hotel.employee table and mine is empty, I guess you need them to login to the page.

So i inserted manualy into hotel.employee table some parameters but still no luck.
Do we have some login credentials hardcoded?

When i try to login in the main page to http://localhost/login instead http://localhost/hotel/login...
App is in <http root>/hotel/. In config.php parameters are set correctly.
Why is it still redirecting me to wrong page?

**Comment by jbiuk** [comment]
After consulting with google,I managed to get pass login page,
First i set up the Rules in .htaccess, and added "RewriteBase /",
then changed apache2.conf file to AllowOverride All for my project folder,
Inserted manualy in the database one user and one department:
then did date/timezone setup in php.ini(because page complained about date :)),

INSERT INTO hotel.department SET department_name="test",department_budget=69;
INSERT INTO hotel.employee SET employee_username="aaa",employee_password="123",employee_firstname="test",employee_type="test",employee_lastname="test",employee_telephone=911,employee_email="test@test.com",department_id=1; 

After that i managed to login and got blank html page... any suggestions?

**Comment by SantiagoSotoC-zz** [comment]
i have the next problem :
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

i'm need your help 
tranks sorry for my english

**Comment by tugbadogan** [comment]
@satiax  That problem is related with Codeigniter and your PHP version. You can find discussion about it from following link.
https://ellislab.com/forums/viewthread/244510/

**Comment by lucianpp** [comment]
hi all,
have anyone managed to setup the app?
