### ISSUE TITLE
Stuck at member login screen

### ISSUE THREAD

**Issue by jayeshcp** [tugbadogan/hotelmanagement#3]
1. Stuck at member login screen. Error says `Your username or password are invalid`.  Default user "admin" doesn't exist in database. I ran `database.sql` file but there are no entries in `employee` table. Tried inserting one entry with `employee_type = admin` but it didn't work.
2. Logs are enabled but not getting generated anywhere.

**Comment by lucianpp** [comment]
hi, please insert a department first and use the department id in user insert.
But how you managed to get to login page? What server you are using?

**Comment by amyou2005** [comment]
I try to find out how to test you app.
Can you help me i always at login page because i don't know how to do.

**Comment by channaveer** [comment]
Its working fine for me....took time to fix minor bugs

**Comment by bodrumbilisim** [comment]
If you fixed can you Share with us?
23 Ara 2015 08:51 tarihinde "Channaveer Hakari" notifications@github.com
yazdı:

**Comment by amyou2005** [comment]
@channaveer pls i looking for you code sharing and better if you write installation instructions.
Thank you

**Comment by channaveer** [comment]
Hi please follow this link which helps you in installation along with database
https://github.com/channaveer/hotel_management

**Comment by iwundu** [comment]
i'm unable to login even with the credentials given can anybody please help me out?
